# This is a basic workflow to help you get started with Actions

name: vars and secrets

env:
  WF_VAR: "Workflow_level_var"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_expressions:
    runs-on: ubuntu-latest
    env:
      BOOLEAN: ${{ false }}
      NULL: ${{ null }}
      NUM: ${{ 12 }}

    steps:
     - name: test null
       if: ${{env.NULL == null}}
       run: echo var is null
       
     - name: test boolean
       if: ${{ fromJSON(env.BOOLEAN) }}
       run: echo var is bool and not run
       
     - name: test num
       if: ${{ env.NUM == 12 && success() }}
       run: sleep(60)
       
     - name: cancelled
       if: ${{ cancelled() }}
       run: echo job is cancelled
      
       
  # This workflow contains a single job called "build"
  test-vars:
    if: (github.event_name == 'pull_request')
    env:
      JOB_VAR: "Job_Level_Var"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Test vars
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo ${{ env.STEP_VAR }}
          echo ${{ vars.REPO_VAR }}
          echo ${{ secrets.REPO_SECRET_A }}
        id: step_var
        env:
          STEP_VAR: "Step_level_var"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: step_2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
